package com.mycompany.view;

import com.mycompany.ferromineraproject.FerromineraProject;
import com.mycompany.service.CommentService;
import com.mycompany.utils.TextPrompt;
import com.mycompany.utils.ValidateInput;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class CommentaryForm extends javax.swing.JPanel {
    
    public int reportId;
    public TextPrompt placeholder;

    /**
     * Creates new form CommentaryForm
     * @param reportId: id del reporte que va a comentar
     */
    public CommentaryForm(int reportId) {
        initComponents();
        this.reportId = reportId;
        placeholder = new TextPrompt("Comentar...", textComment);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        textComment = new javax.swing.JTextArea();
        btnPublish = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 220, 220));

        textComment.setBackground(new java.awt.Color(190, 190, 190));
        textComment.setColumns(20);
        textComment.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textComment.setLineWrap(true);
        textComment.setRows(1);
        textComment.setWrapStyleWord(true);
        textComment.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(200, 200, 200)));
        textComment.setName("Comentario"); // NOI18N
        scroll.setViewportView(textComment);

        btnPublish.setBackground(new java.awt.Color(65, 75, 178));
        btnPublish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/send_logo.png"))); // NOI18N
        btnPublish.setToolTipText("Enviar Comentario");
        btnPublish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnPublish, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll)
                    .addComponent(btnPublish, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //* Validar e insertar el comentario a la DB
    private void btnPublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublishActionPerformed
        try {
            ValidateInput.isEmptyOrBlank(List.of(textComment));
            
            String content = textComment.getText();
            int userId = FerromineraProject.user.getId();
            
            CommentService comService = new CommentService();
            comService.createComment(content, userId, reportId);
            
            ScrollReportContent reportsContent = new ScrollReportContent(reportId);
            
            FerromineraProject.contentP.setPanel(reportsContent);
            FerromineraProject.contentP.showPanel();
            
            reportsContent.initReportCommentContent();
            
        } catch(SQLException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Ocurrio un Error en la conexión con la Base de Datos","ERROR",JOptionPane.ERROR_MESSAGE);
        } catch(Exception e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"No se puede avanzar \n" + e.getMessage(),"Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPublishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPublish;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextArea textComment;
    // End of variables declaration//GEN-END:variables
}
