package com.mycompany.view;

import com.itextpdf.text.Font;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.BadElementException;
import com.mycompany.service.ReportService;
import com.mycompany.utils.PDFGenerator;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.WeekFields;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class PDFGeneratorFilter extends javax.swing.JPanel {

    /**
     * Creates new form PDFGeneratorFilter
     */
    public PDFGeneratorFilter() {
        initComponents();
        
        calendar.setLocale(new Locale.Builder().setLanguage("es").setRegion("ES").build());
        
        calendar.revalidate();
        calendar.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDate = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        labelCalendar = new javax.swing.JLabel();
        separatorCalendar = new javax.swing.JSeparator();
        panelCalendar = new javax.swing.JPanel();
        calendar = new com.toedter.calendar.JCalendar();
        btnRadioMonth = new javax.swing.JRadioButton();
        btnRadioWeek = new javax.swing.JRadioButton();
        btnGeneratePDF = new javax.swing.JButton();

        setBackground(new java.awt.Color(230, 230, 230));

        title.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(65, 75, 178));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Filtros");
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(65, 75, 178)));
        title.setMaximumSize(new java.awt.Dimension(375, 32));

        labelCalendar.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelCalendar.setForeground(new java.awt.Color(65, 75, 178));
        labelCalendar.setText("Seleccionar Año, Mes o un día de la semana para generar informe");

        separatorCalendar.setForeground(new java.awt.Color(65, 75, 178));

        panelCalendar.setBackground(new java.awt.Color(230, 230, 230));
        panelCalendar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(65, 75, 178)));

        calendar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        calendar.setMaxSelectableDate(new Date());

        javax.swing.GroupLayout panelCalendarLayout = new javax.swing.GroupLayout(panelCalendar);
        panelCalendar.setLayout(panelCalendarLayout);
        panelCalendarLayout.setHorizontalGroup(
            panelCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalendarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendar, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCalendarLayout.setVerticalGroup(
            panelCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalendarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendar, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );

        btnGroupDate.add(btnRadioMonth);
        btnRadioMonth.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        btnRadioMonth.setForeground(new java.awt.Color(65, 75, 178));
        btnRadioMonth.setSelected(true);
        btnRadioMonth.setText("Mes");
        btnRadioMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnGroupDate.add(btnRadioWeek);
        btnRadioWeek.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        btnRadioWeek.setForeground(new java.awt.Color(65, 75, 178));
        btnRadioWeek.setText("Semana");
        btnRadioWeek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnGeneratePDF.setBackground(new java.awt.Color(65, 75, 178));
        btnGeneratePDF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnGeneratePDF.setForeground(new java.awt.Color(255, 255, 255));
        btnGeneratePDF.setText("Generar");
        btnGeneratePDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGeneratePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRadioMonth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRadioWeek))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCalendar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separatorCalendar))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(btnGeneratePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(labelCalendar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadioMonth)
                    .addComponent(btnRadioWeek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGeneratePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    //* Generar PDF sobre informe mensual/semanal de los reportes publicados
    private void btnGeneratePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePDFActionPerformed
        String plusName = "", title = "Informe ";
        PDFGenerator generator = null;
        try {
            List<Object[]> reports;
            List<String[]> countReports;
            ReportService reportService = new ReportService();
            Font titleFont = new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD), periodFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD),
                    dateFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL), summaryFont = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD),
                    totalFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD), totalValueFont = new Font(Font.FontFamily.HELVETICA, 14, Font.NORMAL);
            LocalDate localDate = calendar.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
            if(btnRadioMonth.isSelected()) {
                countReports = reportService.getCountReportsInMount(calendar.getDate());
                reports = reportService.getReportsInMonth(calendar.getDate());
                title += "Mensual ";
            } else {
                countReports = reportService.getCountReportsInWeek(calendar.getDate());
                reports = reportService.getReportsInWeek(calendar.getDate());
                plusName = "Semana-" + Integer.toString(localDate.get(WeekFields.of(Locale.getDefault()).weekOfWeekBasedYear())) + "-";
                title += "Semanal ";
            }
            
            plusName += "Mes-" + Integer.toString(localDate.getMonthValue()) + "-" + Integer.toString(calendar.getCalendar().getWeekYear());
            
            generator = new PDFGenerator("informe-" + plusName);
            
            generator.createDocument();
            
            generator.insertTableHeaderImage(getClass().getResource("/cvg_logo.png"), getClass().getResource("/ferrominera_logo.png"), 80, 50);
            
            generator.insertText(title + "de Reportes de Novedades Ferrominera Orinoco", titleFont, 20);
            
            generator.insertTextAndValue("Periodo", plusName, periodFont, dateFont,10);
            
            generator.insertText("Resumen General", summaryFont, 10);
            generator.insertTextAndValue("\tTotal de reportes publicados", Integer.toString(reports.size()), totalFont, totalValueFont, 7);
            
            generator.insertTextsAndValues(countReports, periodFont, dateFont, 5);
            
            generator.insertText("Detalle de Novedades", summaryFont, 10);
            generator.insertReportTable(reports);
            
            JOptionPane.showMessageDialog(null,"El PDF a sido generado con exito con el nombre de: informe-" + plusName,"Info",JOptionPane.INFORMATION_MESSAGE);
            
        } catch(SQLException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Ocurrio un Error en la conexión con la Base de Datos","ERROR",JOptionPane.ERROR_MESSAGE);
        } catch (BadElementException e) {
            System.err.println("Error: Elemento inválido añadido al documento.");
        }  catch (FileNotFoundException e) {
            System.err.println("Error: No se puede crear el archivo. Verifica la ruta y permisos.");
        } catch (DocumentException e) {
            System.err.println("Error: Operación inválida en el documento PDF.");
        } catch (IOException e) {
            System.err.println("Error: Problema al leer o escribir un archivo.");
        } finally {
            if(generator != null) generator.closeDocument();
        }
    }//GEN-LAST:event_btnGeneratePDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneratePDF;
    private javax.swing.ButtonGroup btnGroupDate;
    private javax.swing.JRadioButton btnRadioMonth;
    private javax.swing.JRadioButton btnRadioWeek;
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JLabel labelCalendar;
    private javax.swing.JPanel panelCalendar;
    private javax.swing.JSeparator separatorCalendar;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
