package com.mycompany.view;

import com.mycompany.ferromineraproject.FerromineraProject;
import com.mycompany.models.Novelties;
import com.mycompany.service.NoveltiesService;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Cristian
 */
public class ReportFilter extends javax.swing.JPanel {
    
    /**
     * novelties: listado de objetos que contiene los nombres de cada una de las novedades
     */
    
    public List<Novelties> novelties;

    /**
     * Creates new form ReportFilter
     */
    public ReportFilter() {
        initComponents();
        AutoCompleteDecorator.decorate(selectNew);
        try {
            
            NoveltiesService novService = new NoveltiesService();
            novelties = novService.getNovelties();
            
            for(Novelties nov: novelties)
                selectNew.addItem(nov.getName());
            
        } catch(SQLException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Ocurrio un Error en la conexión con la Base de Datos","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        labelDate1 = new javax.swing.JLabel();
        separatorDate1 = new javax.swing.JSeparator();
        panelDate1 = new javax.swing.JPanel();
        calendar1 = new com.toedter.calendar.JCalendar();
        labelPublisherData = new javax.swing.JLabel();
        separatorPublisherData = new javax.swing.JSeparator();
        panelPublisherData = new javax.swing.JPanel();
        labelPublisherUsername = new javax.swing.JLabel();
        separatorPublisherUsername = new javax.swing.JSeparator();
        inputPublisherUsername = new javax.swing.JTextField();
        labelPublisherFicha = new javax.swing.JLabel();
        separatorPublisherFicha = new javax.swing.JSeparator();
        inputPublisherFicha = new javax.swing.JTextField();
        labelSchedule = new javax.swing.JLabel();
        separatorSchedule = new javax.swing.JSeparator();
        selectSchedule = new javax.swing.JComboBox<>();
        labelNew = new javax.swing.JLabel();
        separatorNew = new javax.swing.JSeparator();
        selectNew = new javax.swing.JComboBox<>();
        check = new javax.swing.JCheckBox();
        checkDate = new javax.swing.JCheckBox();
        labelDate2 = new javax.swing.JLabel();
        separatorDate2 = new javax.swing.JSeparator();
        panelDate2 = new javax.swing.JPanel();
        calendar2 = new com.toedter.calendar.JCalendar();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(230, 230, 230));
        setPreferredSize(new java.awt.Dimension(869, 720));

        title.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(65, 75, 178));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Filtros");
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(65, 75, 178)));
        title.setMaximumSize(new java.awt.Dimension(375, 32));

        labelDate1.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelDate1.setForeground(new java.awt.Color(65, 75, 178));
        labelDate1.setText("Fecha 1:");

        separatorDate1.setForeground(new java.awt.Color(65, 75, 178));

        panelDate1.setBackground(new java.awt.Color(230, 230, 230));
        panelDate1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(65, 75, 178)));
        panelDate1.setPreferredSize(new java.awt.Dimension(350, 190));

        calendar1.setMaxSelectableDate(new Date());

        javax.swing.GroupLayout panelDate1Layout = new javax.swing.GroupLayout(panelDate1);
        panelDate1.setLayout(panelDate1Layout);
        panelDate1Layout.setHorizontalGroup(
            panelDate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDate1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDate1Layout.setVerticalGroup(
            panelDate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDate1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );

        labelPublisherData.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelPublisherData.setForeground(new java.awt.Color(65, 75, 178));
        labelPublisherData.setText("Datos del publicador");

        separatorPublisherData.setForeground(new java.awt.Color(65, 75, 178));

        panelPublisherData.setBackground(new java.awt.Color(230, 230, 230));
        panelPublisherData.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(65, 75, 178)));
        panelPublisherData.setPreferredSize(new java.awt.Dimension(160, 175));

        labelPublisherUsername.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelPublisherUsername.setForeground(new java.awt.Color(65, 75, 178));
        labelPublisherUsername.setText("Nombre de usuario:");

        separatorPublisherUsername.setForeground(new java.awt.Color(65, 75, 178));

        inputPublisherUsername.setBackground(new java.awt.Color(255, 255, 255));
        inputPublisherUsername.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        inputPublisherUsername.setForeground(new java.awt.Color(40, 40, 40));

        labelPublisherFicha.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelPublisherFicha.setForeground(new java.awt.Color(65, 75, 178));
        labelPublisherFicha.setText("Ficha:");

        separatorPublisherFicha.setForeground(new java.awt.Color(65, 75, 178));

        inputPublisherFicha.setBackground(new java.awt.Color(255, 255, 255));
        inputPublisherFicha.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        inputPublisherFicha.setForeground(new java.awt.Color(40, 40, 40));

        javax.swing.GroupLayout panelPublisherDataLayout = new javax.swing.GroupLayout(panelPublisherData);
        panelPublisherData.setLayout(panelPublisherDataLayout);
        panelPublisherDataLayout.setHorizontalGroup(
            panelPublisherDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPublisherDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPublisherDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorPublisherUsername)
                    .addComponent(inputPublisherUsername)
                    .addComponent(separatorPublisherFicha)
                    .addComponent(inputPublisherFicha)
                    .addGroup(panelPublisherDataLayout.createSequentialGroup()
                        .addGroup(panelPublisherDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPublisherUsername)
                            .addComponent(labelPublisherFicha))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPublisherDataLayout.setVerticalGroup(
            panelPublisherDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPublisherDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPublisherUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorPublisherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPublisherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPublisherFicha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorPublisherFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPublisherFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelSchedule.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelSchedule.setForeground(new java.awt.Color(65, 75, 178));
        labelSchedule.setText("Horario:");

        separatorSchedule.setForeground(new java.awt.Color(65, 75, 178));

        selectSchedule.setBackground(new java.awt.Color(255, 255, 255));
        selectSchedule.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        selectSchedule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "7am - 3pm", "3pm - 11pm", "11pm 7am" }));

        labelNew.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelNew.setForeground(new java.awt.Color(65, 75, 178));
        labelNew.setText("Novedad:");

        separatorNew.setForeground(new java.awt.Color(65, 75, 178));

        selectNew.setBackground(new java.awt.Color(255, 255, 255));
        selectNew.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        selectNew.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera" }));

        check.setBackground(new java.awt.Color(230, 230, 230));
        check.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        check.setForeground(new java.awt.Color(65, 75, 178));
        check.setText("Reporte Checado");
        check.setToolTipText("");
        check.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        checkDate.setBackground(new java.awt.Color(230, 230, 230));
        checkDate.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        checkDate.setForeground(new java.awt.Color(65, 75, 178));
        checkDate.setText("Sin Fechas");
        checkDate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDateActionPerformed(evt);
            }
        });

        labelDate2.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelDate2.setForeground(new java.awt.Color(65, 75, 178));
        labelDate2.setText("Fecha 2:");

        separatorDate2.setForeground(new java.awt.Color(65, 75, 178));

        panelDate2.setBackground(new java.awt.Color(230, 230, 230));
        panelDate2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(65, 75, 178)));
        panelDate2.setForeground(new java.awt.Color(65, 75, 178));
        panelDate2.setPreferredSize(new java.awt.Dimension(350, 190));
        panelDate2.setRequestFocusEnabled(false);

        calendar2.setMaxSelectableDate(new Date());

        javax.swing.GroupLayout panelDate2Layout = new javax.swing.GroupLayout(panelDate2);
        panelDate2.setLayout(panelDate2Layout);
        panelDate2Layout.setHorizontalGroup(
            panelDate2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDate2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDate2Layout.setVerticalGroup(
            panelDate2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDate2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendar2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );

        btnSearch.setBackground(new java.awt.Color(65, 75, 178));
        btnSearch.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Buscar");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPublisherData)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(separatorPublisherData)
                    .addComponent(panelPublisherData, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSchedule)
                            .addComponent(selectSchedule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(separatorSchedule))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectNew, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(separatorNew)
                            .addComponent(labelNew)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkDate)
                        .addGap(56, 56, 56)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDate1)
                    .addComponent(panelDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separatorDate1)
                    .addComponent(labelDate2)
                    .addComponent(separatorDate2)
                    .addComponent(panelDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separatorDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDate2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separatorDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPublisherData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separatorPublisherData, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPublisherData, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSchedule)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separatorSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separatorNew, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(check)
                            .addComponent(checkDate))
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //* Enlistar todas los campos y valores para aplicar una sentencia con la busqueda en al DB
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        List<String[]> sentencesAndValues = new ArrayList<>();
        
        String username = inputPublisherUsername.getText(),
                ficha = inputPublisherFicha.getText(), schedule = (String) selectSchedule.getSelectedItem();
        
        if(!checkDate.isSelected()) {
            if(new SimpleDateFormat("yyyy-MM-dd").format(calendar1.getDate()).equals(new SimpleDateFormat("yyyy-MM-dd").format(calendar2.getDate()))) {
                sentencesAndValues.add(new String[]{"DATE(r.create_at) = ? ", new SimpleDateFormat("yyyy-MM-dd").format(calendar1.getDate())});
            } else if(calendar1.getDate().after(calendar2.getDate())) {
                sentencesAndValues.add(new String[]{"DATE(r.create_at) <= ? ", new SimpleDateFormat("yyyy-MM-dd").format(calendar1.getDate())});
                sentencesAndValues.add(new String[]{"DATE(r.create_at) >= ? ", new SimpleDateFormat("yyyy-MM-dd").format(calendar2.getDate())});
            } else {
                sentencesAndValues.add(new String[]{"DATE(r.create_at) <= ? ", new SimpleDateFormat("yyyy-MM-dd").format(calendar2.getDate())});
                sentencesAndValues.add(new String[]{"DATE(r.create_at) >= ? ", new SimpleDateFormat("yyyy-MM-dd").format(calendar1.getDate())});
            }
        }
        
        if((!username.isEmpty()) && (!username.isBlank())) sentencesAndValues.add(new String[]{"user.username LIKE ? ", "%"+ username +"%"});
        
        if((!ficha.isEmpty()) && (!ficha.isBlank())) sentencesAndValues.add(new String[]{"pd.ficha = ? ", ficha});
        
        if(selectSchedule.getSelectedIndex()!=0) sentencesAndValues.add(new String[]{"r.schedule = ? ", schedule});
        
        if(selectNew.getSelectedIndex()!=0)
            for(Novelties nov: novelties)
                if(nov.getName().equals(selectNew.getSelectedItem())) {
                    sentencesAndValues.add(new String[]{"r.novelties_id = ? ", "" + nov.getId()});
                }
        
        if(check.isSelected()) sentencesAndValues.add(new String[]{"r.checked = ? ", "1"});
        
        ScrollReportContent reportsContent = new ScrollReportContent(sentencesAndValues);
        
        FerromineraProject.contentP.setPanel(reportsContent);
        FerromineraProject.contentP.showPanel();
    }//GEN-LAST:event_btnSearchActionPerformed

    //* Desactivar los JCalendar
    private void checkDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDateActionPerformed
        if(calendar1.isEnabled()) {
            calendar1.setEnabled(false);
            calendar2.setEnabled(false);
        } else {
            calendar1.setEnabled(true);
            calendar2.setEnabled(true);
            calendar1.setMaxSelectableDate(new Date());
            calendar2.setMaxSelectableDate(new Date());
        }
    }//GEN-LAST:event_checkDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private com.toedter.calendar.JCalendar calendar1;
    private com.toedter.calendar.JCalendar calendar2;
    private javax.swing.JCheckBox check;
    private javax.swing.JCheckBox checkDate;
    private javax.swing.JTextField inputPublisherFicha;
    private javax.swing.JTextField inputPublisherUsername;
    private javax.swing.JLabel labelDate1;
    private javax.swing.JLabel labelDate2;
    private javax.swing.JLabel labelNew;
    private javax.swing.JLabel labelPublisherData;
    private javax.swing.JLabel labelPublisherFicha;
    private javax.swing.JLabel labelPublisherUsername;
    private javax.swing.JLabel labelSchedule;
    private javax.swing.JPanel panelDate1;
    private javax.swing.JPanel panelDate2;
    private javax.swing.JPanel panelPublisherData;
    private javax.swing.JComboBox<String> selectNew;
    private javax.swing.JComboBox<String> selectSchedule;
    private javax.swing.JSeparator separatorDate1;
    private javax.swing.JSeparator separatorDate2;
    private javax.swing.JSeparator separatorNew;
    private javax.swing.JSeparator separatorPublisherData;
    private javax.swing.JSeparator separatorPublisherFicha;
    private javax.swing.JSeparator separatorPublisherUsername;
    private javax.swing.JSeparator separatorSchedule;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
