package com.mycompany.view;

import com.mycompany.ferromineraproject.FerromineraProject;
import com.mycompany.models.Novelties;
import com.mycompany.models.Report;
import com.mycompany.models.ReportEdit;
import com.mycompany.service.NoveltiesService;
import com.mycompany.service.ReportEditService;
import com.mycompany.service.ReportService;
import com.mycompany.utils.ValidateInput;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Cristian
 */
public class ReportForm extends javax.swing.JPanel {
    
    /**
     * novelties: listado de objetos que contiene los nombres de cada una de las novedades
     * report: objeto es instanciado solo cuando el formulario va ser usado para editar el reporte
     */
    
    public List<Novelties> novelties;
    public Report report = null;

    /**
     * Creates new form ReportForm
     */
    public ReportForm() {
        initComponents();
        AutoCompleteDecorator.decorate(selectNew);
        initReportForm();
    }
    
    /**
     * @param report: objeto que contiene los datos del reporte que hay que editar
     */
    public ReportForm(Report report) {
        initComponents();
        this.report = report;
        AutoCompleteDecorator.decorate(selectNew);
        initReportForm();
        setValues();
    }
    
    //* Insertar los datos del reporte seleccionado para editar
    private void setValues() {
        contentText.setText(report.getContent());
        for(Novelties nov: novelties)
            if(nov.getId()==report.getNoveltiesId())
                selectNew.setSelectedItem(nov.getName());
        selectSchedule.setSelectedItem(report.getSchedule());
        title.setText("Editar reporte");
        btnPublish.setText("Editar");
    }
    
    //* Obtener cada uno de los reportes activos para mostrar en este formulario y
    //* en el caso de que sea editar y el reporte contenga una novedad no activa, mostrar esa novedad tambien
    private void initReportForm() {
        try {
            int id = -1;
            
            if(report!=null) id = report.getNoveltiesId();
            
            NoveltiesService novService = new NoveltiesService();
            novelties = novService.getNovelties();
            
            for(Novelties nov: novelties)
                if(nov.isActive() || nov.getId()==id) selectNew.addItem(nov.getName());
            
        } catch(SQLException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Ocurrio un Error en la conexión con la Base de Datos","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormContent = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        scrollTextArea = new javax.swing.JScrollPane();
        contentText = new javax.swing.JTextArea();
        btnPublish = new javax.swing.JButton();
        panelFormType = new javax.swing.JPanel();
        labelSchedule = new javax.swing.JLabel();
        separatorSchedule = new javax.swing.JSeparator();
        selectSchedule = new javax.swing.JComboBox<>();
        labelNew = new javax.swing.JLabel();
        separatorNew = new javax.swing.JSeparator();
        selectNew = new javax.swing.JComboBox<String>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(869, 720));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        panelFormContent.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(236, 80, 80));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Crear reporte");
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(236, 80, 80)));

        contentText.setBackground(new java.awt.Color(255, 255, 255));
        contentText.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        contentText.setForeground(new java.awt.Color(30, 30, 30));
        contentText.setLineWrap(true);
        contentText.setWrapStyleWord(true);
        contentText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(180, 180, 180)));
        contentText.setName("Contenido"); // NOI18N
        scrollTextArea.setViewportView(contentText);

        btnPublish.setBackground(new java.awt.Color(65, 75, 178));
        btnPublish.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPublish.setForeground(new java.awt.Color(255, 255, 255));
        btnPublish.setText("Publicar");
        btnPublish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPublish.setMaximumSize(new java.awt.Dimension(135, 39));
        btnPublish.setPreferredSize(new java.awt.Dimension(124, 45));
        btnPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormContentLayout = new javax.swing.GroupLayout(panelFormContent);
        panelFormContent.setLayout(panelFormContentLayout);
        panelFormContentLayout.setHorizontalGroup(
            panelFormContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPublish, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormContentLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panelFormContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollTextArea))
                .addGap(76, 76, 76))
        );
        panelFormContentLayout.setVerticalGroup(
            panelFormContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormContentLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(53, 53, 53)
                .addComponent(scrollTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnPublish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        panelFormType.setBackground(new java.awt.Color(230, 230, 230));
        panelFormType.setMinimumSize(new java.awt.Dimension(271, 0));
        panelFormType.setPreferredSize(new java.awt.Dimension(271, 720));

        labelSchedule.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelSchedule.setForeground(new java.awt.Color(65, 75, 178));
        labelSchedule.setText("Horario:");

        separatorSchedule.setForeground(new java.awt.Color(65, 75, 178));

        selectSchedule.setBackground(new java.awt.Color(255, 255, 255));
        selectSchedule.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        selectSchedule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7am - 3pm", "3pm - 11pm", "11pm - 7am" }));
        selectSchedule.setName("Horario"); // NOI18N

        labelNew.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelNew.setForeground(new java.awt.Color(65, 75, 178));
        labelNew.setText("Novedad:");

        separatorNew.setForeground(new java.awt.Color(65, 75, 178));

        selectNew.setBackground(new java.awt.Color(255, 255, 255));
        selectNew.setEditable(true);
        selectNew.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        selectNew.setName("Novedad"); // NOI18N

        javax.swing.GroupLayout panelFormTypeLayout = new javax.swing.GroupLayout(panelFormType);
        panelFormType.setLayout(panelFormTypeLayout);
        panelFormTypeLayout.setHorizontalGroup(
            panelFormTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormTypeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelFormTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormTypeLayout.createSequentialGroup()
                        .addComponent(labelNew)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormTypeLayout.createSequentialGroup()
                        .addGroup(panelFormTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selectNew, javax.swing.GroupLayout.Alignment.LEADING, 0, 211, Short.MAX_VALUE)
                            .addComponent(separatorNew, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectSchedule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFormTypeLayout.createSequentialGroup()
                                .addComponent(labelSchedule)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(separatorSchedule, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(30, 30, 30))))
        );
        panelFormTypeLayout.setVerticalGroup(
            panelFormTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormTypeLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(labelSchedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(labelNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorNew, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFormContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFormType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFormType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //* Reescalamiento del panelFormType (barra lateral derecha), para cuando aumente de tamaño la ventana
    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int width = (int) (this.getWidth() * 0.30);
        
        if(width >= panelFormType.getMinimumSize().width ) 
            panelFormType.setPreferredSize(new Dimension(width, this.getHeight()));
        else 
            panelFormType.setPreferredSize(new Dimension(panelFormType.getMinimumSize().width, this.getHeight()));
        
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_formComponentResized
    
    //* Confirmar si el usuario esta usando los inputs y insertar los datos en la DB
    private void btnPublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublishActionPerformed
        ReportService reportService = new ReportService();
        ReportEditService reportEditService = new ReportEditService();
        
        try {
            ValidateInput.isEmptyOrBlank(List.of(contentText));
            
            String content = contentText.getText(), schedule = (String) selectSchedule.getSelectedItem(), novedad = (String) selectNew.getSelectedItem();
            
            Novelties novelty = null;
            for(Novelties nov: novelties)
                if(nov.getName().equals(novedad)) {
                    novelty = nov;
                    break;
                }
            
            if(novelty==null) throw new Exception("Error al seleccionar la novedad");
            
            if(report==null) reportService.createReport(FerromineraProject.user.getId(), novelty.getId(), content, schedule);
            else {
                ReportEdit reportEdit = reportEditService.getReportEdit(report.getId());
                
                reportService.updateReport(report.getId(), novelty.getId(), content, schedule);
                
                if(reportEdit==null)
                    reportEditService.createReportEdit(FerromineraProject.user.getId(), report.getId());
                else
                    reportEditService.updateReportEdit(reportEdit.getId(), FerromineraProject.user.getId());
            }
            
            ScrollReportContent reportsContent = (report==null) ? new ScrollReportContent(): new ScrollReportContent(report.getId());
        
            FerromineraProject.contentP.setPanel(reportsContent);
            FerromineraProject.contentP.showPanel();
        
            if(report!=null) reportsContent.initReportCommentContent();
            
        } catch(SQLException e) {
            try {
                reportEditService.applyRollBack();
            } catch (SQLException ex) { System.err.println(e.getMessage()); }
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Ocurrio un Error en la conexion con la Base de Datos","ERROR",JOptionPane.ERROR_MESSAGE);
        } catch(Exception e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"No se puede avanzar \n" + e.getMessage(),"Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPublishActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPublish;
    private javax.swing.JTextArea contentText;
    private javax.swing.JLabel labelNew;
    private javax.swing.JLabel labelSchedule;
    private javax.swing.JPanel panelFormContent;
    private javax.swing.JPanel panelFormType;
    private javax.swing.JScrollPane scrollTextArea;
    private javax.swing.JComboBox<String> selectNew;
    private javax.swing.JComboBox<String> selectSchedule;
    private javax.swing.JSeparator separatorNew;
    private javax.swing.JSeparator separatorSchedule;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
