package com.mycompany.view;

import com.mycompany.models.Novelties;
import com.mycompany.service.NoveltiesService;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Cristian
 */
public class ReportForm extends javax.swing.JPanel {
    
    public List<Novelties> novelties;

    /**
     * Creates new form ReportForm
     */
    public ReportForm() {
        initComponents();
        try {
            NoveltiesService novService = new NoveltiesService();
            novelties = novService.getNovelties();
            
            for(Novelties nov: novelties)
                selectNew.addItem(nov);
            
            initSelectNew();
            
        } catch(SQLException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Ocurrio un Error en la conexión con la Base de Datos","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void initSelectNew() {
        JTextField inputNew = (JTextField) selectNew.getEditor().getEditorComponent();
        inputNew.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { updateList(); }
            @Override
            public void removeUpdate(DocumentEvent e) { updateList(); }
            @Override
            public void changedUpdate(DocumentEvent e) { updateList(); }

            private void updateList() {
                SwingUtilities.invokeLater(() -> {
                    String text = inputNew.getText();
                    if (text.isEmpty()) {
                        selectNew.setModel(new DefaultComboBoxModel<>(novelties.toArray(new Novelties[0])));
                    } else {
                        List<Novelties> filteredItems = novelties.stream()
                                .filter(item -> item.getName().toLowerCase().contains(text.toLowerCase()))
                                .collect(Collectors.toList());
                        selectNew.setModel(new DefaultComboBoxModel<>(filteredItems.toArray(new Novelties[0])));
                        selectNew.showPopup();
                    }
                });
            }
        });
        
        selectNew.addActionListener(e -> {
            if (e.getActionCommand().equals("comboBoxEdited")) {
                Novelties selected = (Novelties) selectNew.getSelectedItem();
                selectNew.setModel(new DefaultComboBoxModel<>(novelties.toArray(new Novelties[0])));
                selectNew.setSelectedItem(selected);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormContent = new javax.swing.JPanel();
        inputTitle = new javax.swing.JTextField();
        scrollTextArea = new javax.swing.JScrollPane();
        contentText = new javax.swing.JTextArea();
        btnPublish = new javax.swing.JButton();
        panelFormType = new javax.swing.JPanel();
        labelHours = new javax.swing.JLabel();
        separatorHours = new javax.swing.JSeparator();
        selectHours = new javax.swing.JComboBox<>();
        labelNew = new javax.swing.JLabel();
        separatorNew = new javax.swing.JSeparator();
        selectNew = new javax.swing.JComboBox<Novelties>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(869, 720));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        panelFormContent.setBackground(new java.awt.Color(255, 255, 255));

        inputTitle.setBackground(new java.awt.Color(255, 255, 255));
        inputTitle.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        inputTitle.setForeground(new java.awt.Color(50, 50, 50));
        inputTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputTitle.setText("Titulo");
        inputTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(236, 80, 80)));

        contentText.setBackground(new java.awt.Color(255, 255, 255));
        contentText.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        contentText.setForeground(new java.awt.Color(30, 30, 30));
        contentText.setLineWrap(true);
        contentText.setWrapStyleWord(true);
        contentText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(180, 180, 180)));
        scrollTextArea.setViewportView(contentText);

        btnPublish.setBackground(new java.awt.Color(65, 75, 178));
        btnPublish.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPublish.setForeground(new java.awt.Color(255, 255, 255));
        btnPublish.setText("Publicar");
        btnPublish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPublish.setMaximumSize(new java.awt.Dimension(135, 39));
        btnPublish.setPreferredSize(new java.awt.Dimension(124, 45));

        javax.swing.GroupLayout panelFormContentLayout = new javax.swing.GroupLayout(panelFormContent);
        panelFormContent.setLayout(panelFormContentLayout);
        panelFormContentLayout.setHorizontalGroup(
            panelFormContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormContentLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panelFormContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollTextArea)
                    .addComponent(inputTitle))
                .addGap(76, 76, 76))
            .addGroup(panelFormContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPublish, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFormContentLayout.setVerticalGroup(
            panelFormContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormContentLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(inputTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(scrollTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnPublish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        panelFormType.setBackground(new java.awt.Color(230, 230, 230));
        panelFormType.setMinimumSize(new java.awt.Dimension(271, 0));
        panelFormType.setPreferredSize(new java.awt.Dimension(271, 720));

        labelHours.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelHours.setForeground(new java.awt.Color(65, 75, 178));
        labelHours.setText("Horario:");

        separatorHours.setForeground(new java.awt.Color(65, 75, 178));

        selectHours.setBackground(new java.awt.Color(255, 255, 255));
        selectHours.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        selectHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "Diurno", "Nocturno" }));

        labelNew.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        labelNew.setForeground(new java.awt.Color(65, 75, 178));
        labelNew.setText("Novedad:");

        separatorNew.setForeground(new java.awt.Color(65, 75, 178));

        selectNew.setBackground(new java.awt.Color(255, 255, 255));
        selectNew.setEditable(true);
        selectNew.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        javax.swing.GroupLayout panelFormTypeLayout = new javax.swing.GroupLayout(panelFormType);
        panelFormType.setLayout(panelFormTypeLayout);
        panelFormTypeLayout.setHorizontalGroup(
            panelFormTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormTypeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelFormTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormTypeLayout.createSequentialGroup()
                        .addComponent(labelNew)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormTypeLayout.createSequentialGroup()
                        .addGroup(panelFormTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selectNew, javax.swing.GroupLayout.Alignment.LEADING, 0, 211, Short.MAX_VALUE)
                            .addComponent(separatorNew, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectHours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFormTypeLayout.createSequentialGroup()
                                .addComponent(labelHours)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(separatorHours, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(30, 30, 30))))
        );
        panelFormTypeLayout.setVerticalGroup(
            panelFormTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormTypeLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(labelHours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorHours, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(labelNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorNew, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFormContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFormType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFormType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //* Reescalamiento del panelFormType (barra lateral derecha), para cuando aumente de tamaño la ventana
    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        int width = (int) (this.getWidth() * 0.30);
        
        if(width >= panelFormType.getMinimumSize().width ) 
            panelFormType.setPreferredSize(new Dimension(width, this.getHeight()));
        else 
            panelFormType.setPreferredSize(new Dimension(panelFormType.getMinimumSize().width, this.getHeight()));
        
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPublish;
    private javax.swing.JTextArea contentText;
    private javax.swing.JTextField inputTitle;
    private javax.swing.JLabel labelHours;
    private javax.swing.JLabel labelNew;
    private javax.swing.JPanel panelFormContent;
    private javax.swing.JPanel panelFormType;
    private javax.swing.JScrollPane scrollTextArea;
    private javax.swing.JComboBox<String> selectHours;
    private javax.swing.JComboBox<Novelties> selectNew;
    private javax.swing.JSeparator separatorHours;
    private javax.swing.JSeparator separatorNew;
    // End of variables declaration//GEN-END:variables
}
