package com.mycompany.view;

import com.mycompany.ferromineraproject.FerromineraProject;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Cristian
 */
public class ScrollReportContent extends javax.swing.JPanel {
    
    /**
     * Creates new form ScrollPublishContent
     */
    public ScrollReportContent() {
        initComponents();
    }
    
    public static void InitReportContent() {
        List<JPanel> reports = new ArrayList<>();
        
        for(int i = 0; i <  20; i++) 
            reports.add(new Report());
        
        try {
            FerromineraProject.contentP.ShowItemsPanel(reports);
        } catch (Exception e) { System.err.println(e.getMessage()); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        reportContent = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(869, 720));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        scroll.setBorder(null);

        reportContent.setBackground(new java.awt.Color(255, 255, 255));
        reportContent.setPreferredSize(new java.awt.Dimension(600, 720));

        javax.swing.GroupLayout reportContentLayout = new javax.swing.GroupLayout(reportContent);
        reportContent.setLayout(reportContentLayout);
        reportContentLayout.setHorizontalGroup(
            reportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        reportContentLayout.setVerticalGroup(
            reportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        scroll.setViewportView(reportContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        try {
            FerromineraProject.contentP.ResizeScrollPane();
        } catch(Exception e) { System.err.println(e.getMessage()); }
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel reportContent;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
