package com.mycompany.view;

import com.mycompany.ferromineraproject.FerromineraProject;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Cristian
 */
public class ScrollUserContent extends javax.swing.JPanel {
    
    public UserForm searchUserForm, addUserForm, editUserForm; 

    /**
     * Creates new form Scroll
     */
    public ScrollUserContent() {
        initComponents();
        
        searchUserForm = new UserForm(true, "Buscar");
        addUserForm = new UserForm(false, "Añadir");
        editUserForm = new UserForm(false, "Editar");
        
        btnUserAdd.setSize(30, 31);
        btnUserSearch.setSize(30, 31);
        
        scroll.getVerticalScrollBar().addAdjustmentListener(new AdjustmentListener() {
            @Override
            public void adjustmentValueChanged(AdjustmentEvent e) {
                // Actualizar la posición del botón sticky
                changePosition();
            }
        });
    }
    
    //* Añadir lista de paneles que contienen informacion de los usuarios
    public static void initUserContent() {
        List<JPanel> reports = new ArrayList<>();
        
        for(int i = 0; i <  20; i++) 
            reports.add(new User());
        
        try {
            FerromineraProject.contentP.showItemsPanel(reports);
        } catch (Exception e) { System.err.println(e.getMessage()); }
    }
    
    //* Cambiar de posicion a los stickyBtn (add y search) y sus respectivos formularios
    private void changePosition() {
        Dimension viewport = scroll.getViewport().getSize();
            
        Point p = new Point(viewport.width - 35, viewport.height - 100 + scroll.getVerticalScrollBar().getValue());
        
        btnUserSearch.setLocation(p.x, p.y);
        btnUserAdd.setLocation(p.x - btnUserSearch.getSize().width - 10, p.y);
        
        if(searchUserForm.active)
            formActive(searchUserForm, viewport);
        else if(addUserForm.active)
            formActive(addUserForm, viewport);
        else if(editUserForm.active)
            formActive(editUserForm, viewport);
    }
    
    //* Activar|Mostrar los formularios (add, search o edit)
    private void formActive(UserForm form, Dimension viewport) {
        form.setSize(new Dimension(365, viewport.height));
        form.setLocation(viewport.width - 365, scroll.getVerticalScrollBar().getValue());
        form.revalidate();
        form.repaint();
    }
    
    //* Cambiar la Visibilidad a los stickyBtn
    private void btnVisible(boolean active) {
        btnUserAdd.setVisible(active);
        btnUserSearch.setVisible(active);
    }
    
    //* Funcion que se usa desde el item que se presiona el btnEdit
    public void activeEditUserForm() {
        btnVisible(false);
        editUserForm.active = true;
        userContent.add(editUserForm, 0);
        changePosition();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        userContent = new javax.swing.JPanel();
        btnUserSearch = new javax.swing.JButton();
        btnUserAdd = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 720));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        scroll.setBorder(null);

        userContent.setBackground(new java.awt.Color(255, 255, 255));
        userContent.setPreferredSize(new java.awt.Dimension(600, 600));
        userContent.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                userContentComponentRemoved(evt);
            }
        });

        btnUserSearch.setBackground(new java.awt.Color(180, 180, 180));
        btnUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_logo-black.png"))); // NOI18N
        btnUserSearch.setToolTipText("Buscar Usuario");
        btnUserSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSearchActionPerformed(evt);
            }
        });

        btnUserAdd.setBackground(new java.awt.Color(180, 180, 180));
        btnUserAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-plus_logo.png"))); // NOI18N
        btnUserAdd.setToolTipText("Añadir Usuario");
        btnUserAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userContentLayout = new javax.swing.GroupLayout(userContent);
        userContent.setLayout(userContentLayout);
        userContentLayout.setHorizontalGroup(
            userContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContentLayout.createSequentialGroup()
                .addContainerGap(762, Short.MAX_VALUE)
                .addComponent(btnUserAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUserSearch)
                .addGap(25, 25, 25))
        );
        userContentLayout.setVerticalGroup(
            userContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userContentLayout.createSequentialGroup()
                .addContainerGap(599, Short.MAX_VALUE)
                .addGroup(userContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUserAdd)
                    .addComponent(btnUserSearch))
                .addGap(90, 90, 90))
        );

        scroll.setViewportView(userContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        try {
            FerromineraProject.contentP.resizeScrollPane();
            changePosition();
        } catch(Exception e) { System.err.println(e.getMessage()); }
    }//GEN-LAST:event_formComponentResized

    private void btnUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAddActionPerformed
        // TODO add your handling code here:
        btnVisible(false);
        addUserForm.active = true;
        userContent.add(addUserForm, 0);
        changePosition();
    }//GEN-LAST:event_btnUserAddActionPerformed

    private void btnUserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSearchActionPerformed
        // TODO add your handling code here:
        btnVisible(false);
        searchUserForm.active = true;
        userContent.add(searchUserForm, 0);
        changePosition();
    }//GEN-LAST:event_btnUserSearchActionPerformed
    
    private void userContentComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_userContentComponentRemoved
        // TODO add your handling code here:
        btnVisible(true);
    }//GEN-LAST:event_userContentComponentRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUserAdd;
    private javax.swing.JButton btnUserSearch;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel userContent;
    // End of variables declaration//GEN-END:variables
}
